# Generated by Django 3.2.7 on 2023-01-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='videos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.videos'),
            preserve_default=False,
        ),
    ]
