# Generated by Django 3.2.7 on 2023-01-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230111_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='videos',
        ),
        migrations.AddField(
            model_name='videos',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comments'),
        ),
    ]
