# Generated by Django 3.2.7 on 2023-01-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230111_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.videos'),
        ),
        migrations.AddField(
            model_name='videos',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.playlist'),
        ),
    ]
